server:
  port: 8081

spring:
  application:
    name: yard-alchemy-designs
  
  datasource:
    url: jdbc:postgresql://localhost:5432/yard_alchemy
    username: yard_user
    password: yard_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour
      
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.yardalchemy: INFO
    org.flywaydb: INFO

# OpenAPI/Swagger Documentation
springdoc:
  swagger-ui:
    try-it-out-enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
      
# Application specific configuration
app:
  upload:
    directory: uploads
    max-file-size: 10485760 # 10MB in bytes